### ISSUE TITLE
Rename IG to secure-api-gateway via Kustomize

### ISSUE THREAD

**Issue by shaunharrisonFR** [SecureApiGateway/SecureApiGateway#941]
For ~~2.0.0~~ aerosmith we want to rename IG deployment and services to secure-api-gateway, this was difficult for v1.0.0 as we use forgeops IG base files where the name is already defined as IG. 

We should be able to rename this with something like the following

```
patches:
- target:
    kind: StatefulSet
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: bar
```

But will need further testing to ensure nothing else out of our control is relying on the services and metadata being called IG
